Message/app/routes.py
from flask import Blueprint, render_template, request, jsonify
import sys


routes_message = Blueprint('routes_message', __name__)


@routes_message.route('/')
def main_page():

    return render_template("index.html")


@routes_message.route('/sendmessage', methods=['GET', 'POST'])
def send_message():
    from config import Message, session, datetime

    if request.method == 'POST':
        send_username = request.form['send_user']
        receive_user = request.form['receive_user']
        content = request.form['content']

        new_message = Message(send_username=send_username, receive_username=receive_user,
                              content=content, datetime=datetime.utcnow())

        session.add(new_message)
        session.commit()

    return render_template("sendmessage.html")


@routes_message.route('/messagelist', methods=['GET', 'POST'])
def check_list():
    from config import Message, session
    if request.method == 'POST':
        send_username = request.form['send_username']

        messages_sent = session.query(Message).filter_by(
            send_username=send_username).order_by(Message.datetime.desc()).all()

        return render_template("Messagelist.html", messages_sent=messages_sent)

    messages_sent = session.query(Message).order_by(
        Message.datetime.desc()).all()

    return render_template("Messagelist.html", messages_sent=messages_sent)


@routes_message.route('/messagesreceived', methods=['GET', 'POST'])
def received_list():
    from config import Message, session
    if request.method == 'POST':

        receive_username = request.form['receive_username']

        messages_sent = session.query(Message).filter_by(
            receive_username=receive_username).order_by(Message.datetime.desc()).all()

        return render_template("receivelist.html", messages_sent=messages_sent)

    messages_sent = session.query(Message).order_by(
        Message.datetime.desc()).all()

    return render_template("receivelist.html", messages_sent=messages_sent)

# API routes


@routes_message.route('/API/messages/<id>/list', methods=['GET'])
def check_list_API(id):
    from config import Message, session
    receiver_id = id

    # Query messages received by the receiver
    messages_received = (
        session.query(Message)
        .filter_by(receive_username=receiver_id)
        .order_by(Message.datetime.desc())
        .all()
    )
    

    # Initialize lists to store message information
    sender_usernames = []
    datetimes = []
    contents = []

    # Extract information from the messages and populate the lists
    for message in messages_received:
        sender_usernames.append(message.send_username)
        datetimes.append(message.datetime.strftime("%Y-%m-%d %H:%M:%S"))
        contents.append(message.content)

    # Create a list of dictionaries to store message data
    messages_data = []
    for i in range(len(messages_received)):
        message_data = {
            "sender_username": sender_usernames[i],
            "datetime": datetimes[i],
            "content": contents[i],
        }
        messages_data.append(message_data)
    
    

    # Convert the list of message data to JSON
    messages_json = jsonify(messages_data)

    return messages_json


@routes_message.route('/API/sendmessage', methods=['POST'])
def send_message_API():
    from config import Message, session, datetime

    # Get the JSON data from the request
    data = request.get_json()

    if data:
        send_username = data.get('send_username')
        receive_username = data.get('receive_username')
        content = data.get('content')

        if send_username and receive_username and content:
            # Create a new Message object and add it to the database
            new_message = Message(
                send_username=send_username,
                receive_username=receive_username,
                content=content,
                datetime=datetime.utcnow()
            )

            session.add(new_message)
            session.commit()

            return jsonify({"message": "Message sent successfully"})
        else:
            return jsonify({"error": "Incomplete data"})
    else:
        return jsonify({"error": "Invalid JSON data"})

Message/app/templates/Messagelist.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Message List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 20px;
        }

        h1 {
            font-size: 24px;
        }

        h2 {
            font-size: 20px;
        }

        form {
            margin: 20px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"] {
            padding: 5px;
        }

        input[type="submit"] {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            margin-top: 10px;
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 10px;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        h3 {
            font-size: 20px;
            margin-top: 20px;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        a {
            text-decoration: none;
            color: #007BFF;
            font-weight: bold;
            margin: 10px;
        }

        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Message App</h1>
    <h2>Message Sent by a User:</h2>
    <form method="POST">
        <label for="send_username">Username:</label>
        <input type="text" name="send_username" required>
        <br>
        <input type="submit" value="Search">
    </form>
    <h3>Message List:</h3>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>From</th>
                <th>To</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            {% for message in messages_sent %}
                <tr>
                    <td>{{ message.datetime }}</td>
                    <td>{{ message.send_username }}</td>
                    <td>{{ message.receive_username }}</td>
                    <td>{{ message.content }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('routes_message.check_list') }}">Show All Users</a>
    <a href="{{ url_for('routes_message.main_page') }}">Back to Main Page</a>
</body>
</html>

Message/app/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Message app</title>
</head>
<body>
    <h1>Message app</h1>
    <ul>
        
            <li>
                <a href="{{ url_for('routes_message.send_message' )}}"> Send Message </a>
            </li>
            <li>
                <a href="{{ url_for('routes_message.check_list') }}">Message sent List </a>
            </li>
            <li>
                <a href="{{ url_for('routes_message.received_list') }}">Message received List </a>
            </li>
            
    </ul>
</body>
</html>

Message/app/templates/receivelist.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Message List</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 20px;
        }

        h1 {
            font-size: 24px;
        }

        h2 {
            font-size: 20px;
        }

        form {
            margin: 20px;
        }

        label {
            font-weight: bold;
        }

        input[type="text"] {
            padding: 5px;
        }

        input[type="submit"] {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            cursor: pointer;
            margin-top: 10px; /* Add margin to create space below the button */
        }

        input[type="submit"]:hover {
            background-color: #0056b3;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 1px solid #ccc;
            padding: 10px;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        h3 {
            font-size: 20px;
            margin-top: 20px;
        }

        ul {
            list-style: none;
            padding: 0;
        }

        a {
            text-decoration: none;
            color: #007BFF;
            font-weight: bold;
            margin: 10px;
        }

        a:hover {
            color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Message App</h1>
    <h2>Message Received by a User:</h2>
    <form method="POST">
        <label for="receive_username">Username:</label>
        <input type="text" name="receive_username" required>
        <br>
        <input type="submit" value="Search">
    </form>
    <h3>Message List:</h3>
    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>From</th>
                <th>To</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody>
            {% for message in messages_sent %}
                <tr>
                    <td>{{ message.datetime }}</td>
                    <td>{{ message.send_username }}</td>
                    <td>{{ message.receive_username }}</td>
                    <td>{{ message.content }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{{ url_for('routes_message.received_list') }}">Show All Users</a>
    <a href="{{ url_for('routes_message.main_page') }}">Back to Main Page</a>
</body>
</html>

Message/app/templates/sendmessage.html
<!DOCTYPE html>
<html>
<head>
    <title>Check-in</title>
</head>
<body>
    <h1>Check-in Form</h1>
    <form method="POST">
        <label for="send_user">From:</label>
        <input type="text" name="send_user" required>
        <label for="receive_user">To:</label>
        <input type="text" name="receive_user" required>
        <label for="content">Content:</label>
        <input type="text" name="content" required>
        <br>
        <input type="submit" value="Send">
    </form>
    <a href="{{ url_for('routes_message.main_page') }}">Go Back to Main Page</a>
</body>
</html>